apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: adk-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/adk-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "https://your-backend-service-url.run.app"
        resources:
          limits:
            cpu: '1'
            memory: '512Mi'
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com 