# Cloud Build configuration for T1D-Swarm Backend
# Builds and deploys from backend/ directory

steps:
  # Build the Docker image from current directory (backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/t1d-swarm'
      - '.'
    id: 'build-image'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/t1d-swarm'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 't1d-swarm'
      - '--image=gcr.io/$PROJECT_ID/t1d-swarm'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--port=8080'
      - '--set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=true'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars=GOOGLE_CLOUD_LOCATION=us-central1'
      - '--set-env-vars=ENVIRONMENT=production'
      # Note: JUDGE_CODES and other sensitive vars should be set manually
      # or through Secret Manager for security
    id: 'deploy-service'

# Substitutions for environment variables
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 't1d-swarm'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/t1d-swarm' 